import type { Metadata } from "next";
import { Merriweather } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import Footbar from "@/components/shared/Footbar";
import CartCountProvider from "@/context/CartCountProvider";

const merriweather = Merriweather({
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Quick Cart",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${merriweather.className} bg-rose-50`}>
        <CartCountProvider>
          <header>
            <Navbar></Navbar>
          </header>
          <main className="w-full p-4 min-h-screen border border-l-red-400 ml-auto flex justify-center gap-4">
            {children}
          </main>
        </CartCountProvider>
        <footer>
          <Footbar></Footbar>
        </footer>
      </body>
    </html>
  );
}
