import type { Metadata } from "next";
import { Merriweather } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import Footbar from "@/components/shared/Footbar";

const merriweather = Merriweather({
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Quick Cart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${merriweather.className} bg-amber-100`}>
        <header>
          <Navbar></Navbar>
        </header>
        <main className="w-[80%] p-4 h-screen border border-gray-200 ml-auto">{children}</main>
        <footer>
          <Footbar></Footbar>
        </footer>
      </body>
    </html>
  );
}
